### ISSUE TITLE
Document --convert-variants 

### ISSUE THREAD

**Issue by lnrekerle** [phenopackets/phenopacket-tools#114]
The command --convert-variants is not well documented

**Comment by ielis** [comment]
The documentation has been improved both in [API](http://phenopackets.org/phenopacket-tools/apidocs/org.phenopackets.phenopackettools.converter/module-summary.html) and [user guide](https://github.com/phenopackets/phenopacket-tools/blob/main/docs/converting.rst). The updates will go online with the next release.
