### ISSUE TITLE
UCUM IRI prefix

### ISSUE THREAD

**Issue by ielis** [phenopackets/phenopacket-tools#126]
We should add UCUM builder into `Resources`. However, the IRI prefix for UCUM is unclear.

**Comment by cmungall** [comment]
See also: https://github.com/biopragmatics/bioregistry/issues/648

**Comment by ielis** [comment]
@cmungall 
Does the following look good to you?

IRI: `https://units-of-measurement.org/`

The full UCUM `Resource`:
```
{
      "id": "ucum",
      "name": "Unified Code for Units of Measure",
      "url": "https://ucum.org",
      "version": "2.1",
      "namespacePrefix": "UCUM",
      "iriPrefix": "https://units-of-measurement.org/"
    }
```

The following examples from the [Units.tsv](https://github.com/phenopackets/phenopacket-tools/blob/main/constants/Unit.tsv) resolve:
- https://units-of-measurement.org/mol.mL-1
- https://units-of-measurement.org/mg.d-1
- https://units-of-measurement.org/[diop]


However, the `mm[Hg]` **does NOT**
- https://units-of-measurement.org/mm[Hg]
