### ISSUE TITLE
mg/dL duplicate

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-tools#129]
There is a typo here:

id | label | function name
-- | -- | --
UCUM:mg/dL | milligram per day | milligramPerDay()
UCUM:mg/dL | milligram per deciliter | milligramPerDeciliter()

I think the first should be `mg/d`

I'd do a PR but not sure which file is the SoT:

https://github.com/phenopackets/phenopacket-tools/search?q=milligram+per+deciliter

**Comment by ielis** [comment]
Hello @cmungall, this is the source of truth - https://github.com/phenopackets/phenopacket-tools/blob/main/constants/Unit.tsv
