### ISSUE TITLE
UCUM codes should be prefix encoded

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-tools#135]
Currently some of the UCUM CURIEs are not valid CURIEs and don't expand to valid URIs.

I suggest adopting percent encoding as specified here:
https://build.fhir.org/rdf.html#2.1.6.6.7

**Comment by cmungall** [comment]
Just pinging on this, it's really important to get this right, it would be bad if units were not interoperable

**Comment by ielis** [comment]
Hello @cmungall
I would like to resolve this issue but I am not sure how to interpret/adopt the percent encoding.

Can you please suggest an example edit?

**Comment by cmungall** [comment]
see the README here https://github.com/units-of-measurement/units-of-measurement/
