### ISSUE TITLE
duchenne.json does not conform to specification

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-tools#142]
I am using the experimental linkml rendering of phenopackets which has more rigorous validation that protobuf

It finds an error with:

https://github.com/phenopackets/phenopacket-tools/blob/gh-pages/examples/phenopackets/duchenne.json

specifically the variantInterpretation

https://github.com/phenopackets/phenopacket-tools/blob/2cb89661eb35614c6787123c629008f76cf99e64/examples/phenopackets/duchenne.json#L76-L116

lacks an id as specified in the comments here https://phenopacket-schema.readthedocs.io/en/latest/variant.html

**Comment by cmungall** [comment]
also:

- retinoblastoma
- holoprosencephaly5

**Comment by ielis** [comment]
Hi @cmungall 
thanks for pointing this out. Yes, the code that works with VRS-like is a weak spot of the library/app.
We may need to adjust the builders on the go as I am having serious trouble with understanding the VRS specification. I am coming from a VCF/HGVS world and I am not sure how one can map variant types commonly encountered in those nomenclatures.

In #150 I reworked the examples to ensure they are valid according to phenopacket-tools base validator.
