### ISSUE TITLE
pseudoexfoliation.json has both SNOMEDCT and SCTID namespaces

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-tools#161]
```
      "id": "SCTID:414775001",
      "id": "SCTID:397312009",
      "id": "SCTID:397312009",
```

```
      "id": "SNOMEDCT:252886007",
```

It's best to use consistent prefixes. I recommend bioregistry to determine which is canonical:

https://bioregistry.io/registry/snomedct

**Comment by cmungall** [comment]
[linkml-phenopackets](https://github.com/cmungall/linkml-phenopackets) has a command line tool that will detect bad CURIEs and fix them using bioregistry:

```
 p3 normalize-curies examples/Phenopacket-pseudoexfoliation.yaml
p3 normalize-curies examples/Phenopacket-pseudoexfoliation.yaml -o /tmp/Phenopacket-pseudoexfoliation-fixed.yaml
## Num results: 3
## RESULT: ('SCTID:397312009', 'SNOMEDCT:397312009')
## RESULT: ('SCTID:397312009', 'SNOMEDCT:397312009')
## RESULT: ('SCTID:414775001', 'SNOMEDCT:414775001')
```

**Comment by ielis** [comment]
Hi @cmungall thanks a lot for pointing out this issue. I fixed the invalid prefixes and the validation now works OK.
