### ISSUE TITLE
`dateOfBirth` field filled in phenopacket conversion

### ISSUE THREAD

**Issue by yaseminbridges** [phenopackets/phenopacket-tools#177]
Hi,

When converting a v1.0 phenopacket to a v2.0 phenopacket the `dateOfBirth` field is filled with `1970-01-01T00:00:00Z`, even when there is no reference to a `dateOfBirth` in the v1 phenopacket. I am using the latest release (RC1).

Thanks,

Yasemin

**Comment by ielis** [comment]
HI Yasemin,
thanks for the bug report. There is an issue with how the converter is handling default protobuf instances. I'll let you know when I fix it.

**Comment by ielis** [comment]
Hi @yaseminbridges I posted a fix to the latest phenopacket-tools version. Can you please test that it works OK on your data?

Note that you'll have to build the latest code from source, which requires `git` and JDK 17 or better on your system:
```bash
git clone git@github.com:phenopackets/phenopacket-tools.git
cd phenopacket-tools
./mvnw -Prelease clean package
```

This will create a distribution ZIP file in `phenopacket-tools-cli/target` folder. You can use the distribution file to install the bleeding edge phenopacket-tools as described in the [manual](http://phenopackets.org/phenopacket-tools/latest/tutorial.html#download-phenopacket-tools) (unpack the ZIP, set up alias, etc.).

The latest code should provide correct output.

Thanks & cheers,
Daniel

**Comment by ielis** [comment]
Hi @yaseminbridges I posted a fix to the latest phenopacket-tools version. Can you please test that it works OK on your data?

Note that you'll have to build the latest code from source, which requires `git` and JDK 17 or better on your system:
```bash
git clone git@github.com:phenopackets/phenopacket-tools.git
cd phenopacket-tools
./mvnw -Prelease clean package
```

This will create a distribution ZIP file in `phenopacket-tools-cli/target` folder. You can use the distribution file to install the bleeding edge phenopacket-tools as described in the [manual](http://phenopackets.org/phenopacket-tools/latest/tutorial.html#download-phenopacket-tools) (unpack the ZIP, set up alias, etc.).

The latest code should provide correct output.

Thanks & cheers,
Daniel

**Comment by yaseminbridges** [comment]
Hi @ielis, I just tested the latest code (RC3) and it all worked great! The `dateOfBirth` is no longer automatically filled.

Thanks,
Yasemin
