### ISSUE TITLE
Trouble converting interpretations

### ISSUE THREAD

**Issue by gsfk** [phenopackets/phenopacket-tools#198]
Phenopackets v1 has four top-level elements: Phenopacket, Family, Cohort and Interpretation. But the `-e | --element` flag in the v1->v2 converter only accepts the first three as options. It's unclear how I'm supposed to convert an interpretation. I get this or similar errors when attempting: 

`input element (-e | --element) was not provided and element sniffing failed`

Looking through the docs and the code I see interpretations generated using `--convert-variants` but I have no variants or diseases to convert, neither is required for an interpretation. So it's not clear to me that my use case is covered (and adding `--convert-variants` doesn't help).

**Comment by ielis** [comment]
Hi @gsfk 

Phenopacket tools does not support conversion of v1 interpretation at the moment. I could, however, add it and it sounds like you would have some use for it, right?

Is this something you need? Would you be willing to test a patch version if it works OK on your end? Please let me know, thank you!

**Comment by gsfk** [comment]
Hi, sorry, this was only a one-time use for [us](https://github.com/bento-platform), we started using interpretations only when they became a "building block" component so it's unlikely to come up again. So I won't be able to find the time to write a patch anytime soon. 

I came across this when trying to convert phenopackets in this [test dataset](https://ega-archive.org/datasets/EGAD00001008392) to PXF v2.

**Comment by ielis** [comment]
> ... So I won't be able to find the time to write a patch anytime soon.

Actually, I was proposing to write the patch and I wanted you to *test* it

> ... we started using interpretations only when they became a "building block" so it's unlikely to come up again ... 

however, yes, this is why I am not "all in" regarding writing a patch unless you really really need it

> ... this was only a one-time use for [us](https://github.com/bento-platform)

and it seems like you do not really really need it.. :)

So, unless this simplifies your life a lot, I will refrain myself from writing the patch for converting v1 interpretation into a v2 phenopacket or family, and I will close the issue.

Please feel free to reopen/comment should there be a need for converting interpretations.
