### ISSUE TITLE
Add InterpretationConverter interface and implement for CLI

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-tools#29]
Need a way of extracting v1 `disease`, `gene` and `variant` into a v2 `interpretation`.

Enable this in CLI `convert` will need to implement the interface and assume single gene-disease-variant associations or else die.

**Comment by ielis** [comment]
Now we have an option to do this in [V1toV2Converter](https://github.com/phenopackets/phenopacket-tools/blob/9142c120c524d1f8d32c21d8b3ab2712ae4f9be0/phenopacket-tools-converter/src/main/java/org/phenopackets/phenopackettools/converter/converters/V1ToV2Converter.java#L19).

The functionality is available in CLI via `--convert-variants` option:
```shell
cat phenopacket.v1.json | pxf-tools convert --convert-variants > phenopacket.v2.json
```
