### ISSUE TITLE
static constructor naming conventions

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-tools#46]
@pnrobinson I think there was a bit of a misunderstanding  
```java
OntologyClass fwRosette = of("NCIT:C35941", "Flexner-Wintersteiner Rosette Formation");
PhenotypicFeature pfRosette = PhenotypicFeatureBuilder.builder(fwRosette).build();
builder.phenotypicFeature(pfRosette);
OntologyClass apoptosisNecrosis = of("NCIT:C132485", "Apoptosis and Necrosis");
PhenotypicFeature pfApoptosis = PhenotypicFeatureBuilder.builder(apoptosisNecrosis).build();
builder.phenotypicFeature(pfApoptosis);
OntologyClass maxTumorSizeTest = OntologyClassBuilder.of("LOINC:33728-7", "Size.maximum dimension in Tumor");
Value maxTumorSize = ValueBuilder.of(mm(), 15);
Measurement maxTumorSizeMeasurement = MeasurementBuilder.value(maxTumorSizeTest, maxTumorSize).timeObserved(age).build();
```

previously these were names like so

```java
OntologyClass fwRosette = ontologyClass("NCIT:C35941", "Flexner-Wintersteiner Rosette Formation");
PhenotypicFeature pfRosette = PhenotypicFeatureBuilder.create(fwRosette).build();
builder.phenotypicFeature(pfRosette);
OntologyClass apoptosisNecrosis = ontologyClass("NCIT:C132485", "Apoptosis and Necrosis");
PhenotypicFeature pfApoptosis = PhenotypicFeatureBuilder.create(apoptosisNecrosis).build();
builder.phenotypicFeature(pfApoptosis);
OntologyClass maxTumorSizeTest = OntologyClassBuilder.ontologyClass("LOINC:33728-7", "Size.maximum dimension in Tumor");
Value maxTumorSize = ValueBuilder.value(Unit.mm(), 15);
Measurement maxTumorSizeMeasurement = MeasurementBuilder.value(maxTumorSizeTest, maxTumorSize).timeObserved(age).build();     
```

e.g. 
`Foo.of(...) -> Foo` Ideally we'd like to do this, but we can't as the protoc generated classes don't offer this. So we need to wrap the `Foo.Builder` in a `FooBuilder`, so I originally named the signatures to be consistent with the values they returned, e.g.

`FooBuilder.foo(...) -> Foo` this way you can static import *all* the Foo/Bar/BazBuilders and they still have meaning e.g. foo(...), bar(...), baz(...). Calling them all `FooBuilder.of` prevents that and I think it less meaningful.
`FooBuilder.builder(...) -> FooBuilder`
`FooBuilder.build() -> Foo` 

`FooBuilder.of() -> ?` I'd say this should return a `FooBuilder`, not a `Foo` 

As an aside there are convenience constructors which will create the `OntologyClass` for you, so instead of saying

```java
OntologyClass fwRosette = OntologyClassBuilder.of("NCIT:C35941", "Flexner-Wintersteiner Rosette Formation");
PhenotypicFeature pfRosette = PhenotypicFeatureBuilder.builder(fwRosette).build();
builder.phenotypicFeature(pfRosette);
```
you can say
```java
PhenotypicFeature pfRosette = PhenotypicFeatureBuilder.of("NCIT:C35941", "Flexner-Wintersteiner Rosette Formation");
builder.phenotypicFeature(pfRosette);
PhenotypicFeature pfApoptosis = PhenotypicFeatureBuilder.of("NCIT:C132485", "Apoptosis and Necrosis");
builder.phenotypicFeature(pfApoptosis);
```
If the `PhenotypicFeatureBuilder.of` was called `PhenotypicFeatureBuilder.phenotypicFeature`,  using an `import static PhenotypicFeatureBuilder.phenotypicFeature;` you can express this much more succinctly:

```java
builder
    .phenotypicFeature(phenotypicFeature("NCIT:C35941", "Flexner-Wintersteiner Rosette Formation"))
    .phenotypicFeature(phenotypicFeature("NCIT:C132485", "Apoptosis and Necrosis"))
```

or if we really want to town, we could add that directly into the builders requiring a `PhenotypicFeature`:

```java
builder
    .phenotypicFeature("NCIT:C35941", "Flexner-Wintersteiner Rosette Formation")
    .phenotypicFeature("NCIT:C132485", "Apoptosis and Necrosis")
```

**Comment by pnrobinson** [comment]
Ups, sorry I was meaning to clean this up, the "of" were put in by IntelliJ and should have had the class names attached to them. I changed some of them but missed these!

**Comment by julesjacobsen** [comment]
OK, no problem. I'll go and change them back again.

**Comment by pnrobinson** [comment]
I think this PR got too big. If it is OK, I will go ahead and merge and will make a new branch to continue this work?

**Comment by julesjacobsen** [comment]
Hang on!

**Comment by julesjacobsen** [comment]
OK, sorted now. Merge away.

**Comment by pnrobinson** [comment]
@julesjacobsen thanks!
