### ISSUE TITLE
Rename packages to `phenopacket-tools`

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-tools#48]
'Phenotools' is, in my opinion, a poor name as it is rather generic and nondescript. `Phenopacket-tools` is a bit more specific and I suggest we use this. This would require changing the `groupId` , `artifactId`s and the package names. It will completely break all existing code, so needs to happen before pushing to maven central. 

```xml
    <parent>
        <groupId>org.phenopackets.phenotools</groupId>
        <artifactId>phenotools</artifactId>
        <version>0.0.2-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>phenotools-builder</artifactId>
```

@pnrobinson @ielis any objections?

**Comment by pnrobinson** [comment]
given the domain of phenopackets, we could be a littel more concise with 

```
 <parent>
        <groupId>org.phenopackets.tools</groupId>
        <artifactId>phenopacket-tools</artifactId>
        <version>0.0.2-SNAPSHOT</version>
    </parent>
```
but I agree in any case that ``phenotools`` is suboptimal

**Comment by ielis** [comment]
Sounds good to me, both the new `groupId` and `artifactId` an.

**Comment by julesjacobsen** [comment]
Thanks @pnrobinson  - remember to delete all stale branches now and branch from develop!
