### ISSUE TITLE
Unclear `String identifier` argument for `GeneDescriptorBuilder.builder()` and `GeneDescriptorBuilder.of()`

### ISSUE THREAD

**Issue by ielis** [phenopackets/phenopacket-tools#60]
Both methods `GeneDescriptorBuilder.builder()` and `GeneDescriptorBuilder.of()` take `String identifier` as a parameter. However, there is no field named `identifier` in the schema. The parameters should be renamed to `String valueId` to disambiguate.

**Comment by pnrobinson** [comment]
Fixed by https://github.com/phenopackets/phenopacket-tools/pull/113
