### ISSUE TITLE
Add `AllelicState` into `org.phenopackets.phenopackettools.builder.constants` package?

### ISSUE THREAD

**Issue by ielis** [phenopackets/phenopacket-tools#61]
The `VariationDescriptorBuilder` allows to set the `allelicState` field via `heterozygous()`, `homozygous()` etc. The methods contain hard-coded `GENO` constants. However, it may be useful to define the allelic state constants in a new `org.phenopackets.phenopackettools.builder.constants.AllelicState` class.

**Comment by pnrobinson** [comment]
good suggestion, done!
