### ISSUE TITLE
Ontology validator

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-tools#73]
Somehow some classes got refactored that performed ontology based validation. These classes would do things that are not easy to do with JSON Schema, such as

- check whether a given id actually exists in an ontology
-  check whether the id is a primary id (if not report as warning and show primary id)
- check whether a term is used together with its parent term (should generally not be done with HPO annotations)
- check whether a term is used together with the negation of a parent term (logical error)
- check whether terms from a specific list of organ systems are used (e.g., either NOT abnormal cardiovasclar or a specific term from the cardiovascular hierarchy and so on for a specified list of organ systems.

**Comment by ielis** [comment]
The `HpoPhenotypeValidators.Primary.phenopacketHpoPhenotypeValidator(hpo)` and `HpoPhenotypeValidators.Ancestry.phenopacketHpoAncestryValidator(hpo)` do almost all of that. 

## `HpoPhenotypeValidators.Primary.phenopacketHpoPhenotypeValidator(hpo)`

- [x]  check whether a given id actually exists in an ontology
- [x]   check whether the id is a primary id (if not report as warning and show primary id)

## `HpoPhenotypeValidators.Ancestry.phenopacketHpoAncestryValidator(hpo)`
- [x]  check whether a term is used together with its parent term (should generally not be done with HPO annotations)
- [x]  check whether a term is used together with the negation of a parent term (logical error)

On top of the above checks, the `Ancestry` validator checks if a negated term is used together with its negated parent, and suggests using the least specific term. 

With regards to the ancestry checks, the term and parents are allowed only if the parent term is present and the child term is negated (e.g. Abnormality of finger but NOT Arachnodactyly).

---
The last item of the list above is not yet implemented:
- [ ] check whether terms from a specific list of organ systems are used (e.g., either NOT abnormal cardiovascular or a specific term from the cardiovascular hierarchy and so on for a specified list of organ systems.

Perhaps in the next minor release?

**Comment by pnrobinson** [comment]
@ielis   This seems pretty easy

```
PhenopacketHpoCoverageValidator (Ontology hpo, Set<TermId> requiredTopLevelTerms) {
}

validate() {
// create map<TermId,Boolean> covered....
for PhenotypicFeature feature : component.getPhenotypicFeaturesList() {
   TermId tid = feature.getTermId()
   for (TermId topLevelTid : covered.keySet()) {
      if (OntologyAlgorithm.isAncestor(topLevelTid, tid)) {
          covered.put(topLevelTid, True);
}
}
// check if any term in covered is False and if so emit a warning
}
```

Should we just add a class like this as another example?

**Comment by ielis** [comment]
Done
