### ISSUE TITLE
Setup for the first public release

### ISSUE THREAD

**Issue by ielis** [phenopackets/phenopacket-tools#77]
Setup repo for the first public release. 

Note that running:
```shell
./mvnw --projects phenopacket-tools-builder --also-make deploy
```

deploys only `phenopacket-tools-builder` artifact.

However, the repo needs to be setup for public repositories before releasing. We should add `release` profile that generates javadoc, bundles sources, signs the JAR files.

**Comment by pnrobinson** [comment]
@ielis I think we can close this? Is there still any open action item for this?

**Comment by ielis** [comment]
No, this is done. The entire project builds everywhere and we already have the `release` profile.
