### ISSUE TITLE
version 1 vs v2

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-tools#86]
This command
```
 Phenopacket.parseFrom(jsonString.getBytes());
```
produces the following if we try to parse a v2 phenopacket
```
Invalid Phenopacket Message: Protocol message tag had invalid wire type.
```
This is the expected behavior if we try to unpack the wrong kind of message, but the error message will not be helpful if people are not familiar with protobuf, and also the error message will be the same for any other kind of Message (not just v1 phenopacket). Therefore, it would be good to figure out a way to check if a message is v1 and if so to produce a special error message.

**Comment by pnrobinson** [comment]
@ielis thoughts?

**Comment by ielis** [comment]
The users who use low-level `protobuf-java` have to cope with this scenario. As an alternative, we provide the [phenopacket-tools-io](http://phenopackets.org/phenopacket-tools/stable/apidocs/org.phenopackets.phenopackettools.io/org/phenopackets/phenopackettools/io/package-summary.html) module with [PhenopacketParser](http://phenopackets.org/phenopacket-tools/stable/apidocs/org.phenopackets.phenopackettools.io/org/phenopackets/phenopackettools/io/PhenopacketParser.html) that reads bytes, or an `InputStream` into a `Message` and produces more informative error messages.
