### ISSUE TITLE
Javadoc hosting?

### ISSUE THREAD

**Issue by pnrobinson** [phenopackets/phenopacket-tools#90]
FIgure out where we can host online Javadoc for this library

**Comment by justaddcoffee** [comment]
Does this not belong with the other documentation on github pages?

**Comment by pnrobinson** [comment]
Ideally yes, I did not know that was (easily?) possible? 
I was thinking of something like this -- https://javadoc.io/ and then we would link from the ghpages docs --

**Comment by ielis** [comment]
We deploy phenopacket-tools to Maven Central as part of the release schedule. Thanks to this, Javadocs are hosted automatically on https://javadoc.io.

E.g. for [phenopacket-tools-validator-core](https://javadoc.io/doc/org.phenopackets.phenopackettools/phenopacket-tools-validator-core).

They even provide a badge! :)
[![javadoc](https://javadoc.io/badge2/org.phenopackets.phenopackettools/phenopacket-tools-builder/javadoc.svg)](https://javadoc.io/doc/org.phenopackets.phenopackettools/phenopacket-tools-builder) 

I think we can close the issue

**Comment by pnrobinson** [comment]
+1
